name: Test dotnet-csharp

on:
  push:
    paths:
      - 'dotnet_csharp/**'
      - '.github/workflows/dotnet-csharp.yml'
  pull_request:
    paths:
      - 'dotnet_csharp/**'
      - '.github/workflows/dotnet-csharp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x'
          cache: true
          cache-dependency-path: dotnet_csharp/HeroQuest.Test/packages.lock.json

      - name: Set up dependencies
        working-directory: dotnet_csharp
        run: dotnet restore --locked-mode

      - name: Build and test
        working-directory: dotnet_csharp
        run: dotnet test
