name: Test Java_dataclass

on:
  push:
    paths:
      - 'Java_dataclass/**'
      - '.github/workflows/Java_dataclass.yml'
  pull_request:
    paths:
      - 'Java_dataclass/**'
      - '.github/workflows/Java_dataclass.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [14, 17, 21]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}

    - name: Build and test
      working-directory: Java_dataclass
      run: mvn -B package

    - name: Run
      working-directory: Java_dataclass
      run: mvn compile exec:java
